server:
  port: 9090

spring:
  datasource:
    url: "jdbc:h2:file:./test.db"
    driver-class-name: "org.h2.Driver"
    # driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true